---
application_state: present
application_id: app
application_version: latest
application_image: ''
application_host_port: 8080
application_container_port: 8080
application_bind_address: 127.0.0.1
application_data_path: /var/lib/aggregare/app
application_container_data_path: /data
application_data_paths: []
application_volumes: []
application_data_owner: root
application_data_group: root
application_environment: {}
application_secret_environment: {}
application_user: ''
application_health_path: /
